### ISSUE TITLE
Error Phishing

### ISSUE THREAD

**Issue by ConstantinT** [TROUBLE-1/Vajra#3]
**Description**
When using the phishing module and the victim is redirected to: https://[...].com/azure/getcode/3965[...]f?code=0.AYIAT0FRU5LMWk6duuByeVEJD[...] the browser shows a 500. 

The console of Varja throws the following error:

```
[2023-01-31 13:50:17,168] ERROR in app: Exception on /azure/getcode/3965a7c339a842f8b00ea4e4dda8b07f [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Vajra/Code/vajra/routes.py", line 477, in getcode
    return redirect(f"/azure/getcode/{current_user.id}")
                                      ^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUserMixin' object has no attribute 'id'
```

**Comment by TROUBLE-1** [comment]
Hi,

The following issue has been patched please check and confirm.

Thank you.
